### ISSUE TITLE
ツイート頻度が極度に少ない場合、表がすごく縦長になってしまい表示がおかしくなる

### ISSUE THREAD

**Issue by takanakahiko** [p1ass/midare#21]
取得するツイート数を一定にして実装しているようですが、ツイート数が極端に少ない場合、ものすごく過去のツイートを読んでしまうため表示が壊れてしまいます。
[生活習慣の乱れを可視化するやつ.pdf](https://github.com/p1ass/midare/files/4718970/default.pdf)

ツイート数の上限に加えて、「2週間前まで」みたいな期間的な上限も加えた方が良いかと思われます。

期間さえ決まればこちらからPR投げる形でも構いません。

**Comment by takanakahiko** [comment]
すみません、コメント無しで間違えてたててしまいました。挙動の詳細を記述します。

**Comment by p1ass** [comment]
@takanakahiko バグ報告ありがとうございます！

現状でも
